baseURL: "https://jsitera.github.io/"
languageCode: en-us
title: Siterovi.cz
description: Rodinný rozcestník
author: Jiří Sitera
paginate: 5
theme: PaperMod

params:
  subtitle: Rodinný rozcestník

menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: jiri
      name: Jiří Sitera
      url: /jiri/
      weight: 20
    - identifier: about
      name: About this site
      url: /about/
      weight: 30
