baseURL: "https://jsitera.github.io/"
languageCode: en-us
title: Siterovi.cz
description: Rodinný rozcestník
author: Jiří Sitera
#theme: PaperMod

menus:
  main:
    - name: Home
      weight: 10
      pageRef: /
    - name: Jiří Sitera
      weight: 20
      pageRef: /jiri
    - name: Dess
      weight: 30
      url: https://denisasiterova.wordpress.com/
    - name: Japicraft
      weight: 40
      url: https://meowcraftorg.wordpress.com/
    - name: About
      weight: 50
      pageRef: /about

params:
  subtitle: Rodinný rozcestník
  ui:
    footer_about_disable: false
    navbar_logo: false
  links:
    user:
      - name: Twitter
        url: 'https://twitter.com/jiri_sitera'
        icon: fab fa-twitter
        desc: Twitter/X home page
      - name: Facebook
        url: 'https://www.facebook.com/jiri.sitera'
        icon: fab fa-facebook
        desc: Facebook profile
      - name: Instagram
        url: 'https://www.instagram.com/jiri.sitera/'
        icon: fab fa-instagram
        desc: Instagram profile
      - name: YouTube
        url: 'https://www.youtube.com/channel/UCrxtCpCMUKJkKgousCRyl6Q'
        icon: fab fa-youtube
        desc: Youtube channel
    developer:
      - name: 500px photo gallery
        url: 'https://500px.com/p/sitera'
        icon: fab fa-500px
        desc: 500px photo gallery
      - name: GitHub
        url: 'https://github.com/jsitera'
        icon: fab fa-github
        desc: Github profile
      - name: LinkedIn
        url: 'https://www.linkedin.com/in/jiri-sitera-04890912/'
        icon: fab fa-linkedin
        desc: Personal LinkedIn profile
      - name: User page - University of West Bohemia
        url: 'https://home.zcu.cz/~sitera/'
        icon: fa fa-envelope
        desc: User page - University of West Bohemia




module:
  proxy: direct
  hugoVersion:
    extended: true
    min: 0.73.0
  imports:
    - path: github.com/google/docsy
      disable: false

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    style: tango
